[build]
  base = "shop-demo"
  command = "npm ci && npm run build && npm run export"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"

[context.production.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SITE_URL = "https://oradore.netlify.app"