backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Brand", name: "brand", widget: "string" }
      - { label: "Mechanism", name: "mechanism", widget: "string" }
      - { label: "Features", name: "features", widget: "list" }
      - { label: "Strap Material", name: "strap_material", widget: "string" }
      - { label: "Glass Material", name: "glass_material", widget: "string" }
      - { label: "Case Size", name: "case_size", widget: "string" }
      - {
          label: "Water Resistance",
          name: "water_resistance",
          widget: "string",
        }
      - { label: "Warranty", name: "warranty", widget: "string" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Colors", name: "colors", widget: "list" }
      - { label: "Images", name: "images", widget: "list" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
